vim.g.mapleader = " " -- Set leader key to space
vim.g.maplocalleader = " " -- Set local leader key to space
vim.o.termguicolors = true -- Use colorscheme to set color highlighting
vim.o.number = true -- Show line numbers
vim.o.tabstop = 4 -- 4 spaces is equivalent to 1 tab
vim.o.shiftwidth = 4 -- Number of spaces to use for autoindent
vim.o.shiftround = true -- Round indent to multiple of 'shiftwidth'
vim.o.expandtab = true -- Use spaces instead of tabs
vim.o.smartindent = true -- Smart autoindenting when starting a new line
vim.o.wrap = false -- Prevents text wrap if text extends current window
vim.o.hlsearch = true -- highlighting while searching
vim.o.incsearch = true -- Show match for each character entered during search
vim.o.scrolloff = 8 -- minimal number of screen lines to keep above and below the cursor
vim.o.swapfile = false -- disable creation of swap files
vim.opt.shadafile = "NONE" -- Do not save and restore the shada file
vim.o.updatetime = 250 -- faster completion (4000ms default)
vim.o.cursorline = true -- highlight line where the cursor is
vim.o.numberwidth = 2 -- set number column width to 2 (default is 4)
