return {
  "onsails/lspkind.nvim",
  config = function()
    require("lspkind").init({
      -- a.k.a icons for cmp menu
      symbol_map = {
        Array = "  ",
        Boolean = "  ",
        Class = "  ",
        Color = "  ",
        Constant = "  ",
        Constructor = "  ",
        Enum = "  ",
        EnumMember = "  ",
        Event = "  ",
        Field = "  ",
        File = "  ",
        Folder = "  ",
        Function = "  ",
        Interface = "  ",
        Key = "  ",
        Keyword = "  ",
        Method = "  ",
        Module = "  ",
        Namespace = "  ",
        Null = " ﳠ ",
        Number = "  ",
        Object = "  ",
        Operator = "  ",
        Package = "  ",
        Property = "  ",
        Reference = "  ",
        Snippet = "  ",
        String = "  ",
        Struct = "  ",
        Text = "  ",
        TypeParameter = "  ",
        Unit = "  ",
        Value = "  ",
        Variable = "  ",
      },
    })
  end,
}
